# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ddc08008-7060-43dc-af33-9c79abf421bc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ddc08008-7060-43dc-af33-9c79abf421bc".device = "/dev/disk/by-uuid/ddc08008-7060-43dc-af33-9c79abf421bc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E636-6917";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-34a67564-6b1d-4c48-94db-4320d2169afb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
